### ISSUE TITLE
Changing global spawnpoint breaks for existing players

### ISSUE THREAD

**Issue by amnotbananaama** [DaFuqs/GlobalSpawn#1]
I cannot thank you enough for creating this mod, I've been looking for exactly this mod for more than 3 months! I noticed a handful of bugs, so I thought I would report them. Thank you very much for taking a look, let me know if you need anything from me or if there's anything else I can test.

### Bug 1
If the global spawn point is moved during play, players who die will spawn at the **coordinates** of the new global spawn in the **dimension** of the initial global spawn point. Relogging, doing `globalspawnpoint set` again, restarting the game (or the server), `/setworldspawn`, etc all have no effect. The ONLY ways to change the player's spawn point are using the `/spawnpoint` command (overrides the mod entirely), and triggering Bug 2.

**Reproduction Steps**
_Note: It doesn't matter which dimension(s) are chosen. This phenomenon occurs with [custom dimensions](https://minecraft.gamepedia.com/Custom_dimension) as well as the default 3 dimensions. These steps are meant to demonstrate the issue clearly._

1. Create a normal world with cheats enabled, or make yourself OP in Multiplayer.
2. Set your spawn point in the End. (`/execute in minecraft:the_end run tp @s 0 63 0` then `/globalspawnpoint set`).
3. Teleport to the Overworld and die. (`/execute in minecraft:overworld run tp @s 100 90 100` then `/kill`).
-> ✔️ You respawn at 0 63 0 in `minecraft:the_end`.
4. Set the global spawn anywhere in the Overworld. (`/execute in minecraft:overworld run tp @s -530 90 280` then `/globalspawnpoint set`).
5. Teleport to the Nether and die. (`/execute in minecraft:the_nether run tp @s -400 90 200` then `/kill`).
-> :x: You respawn at -530 90 280 in `minecraft:the_end` (Right coordinates, wrong dimension).

**Comment by DaFuqs** [comment]
Fixed in 1.0.1
