### ISSUE TITLE
[BUG] 1.18.2 - Anyone can set a initial and global spawn point despite not being opped

### ISSUE THREAD

**Issue by MrRubberDucky** [DaFuqs/GlobalSpawn#12]
**Describe the bug**
Seems like everyone, even those without permissions can still do /initialspawnpoint set and /globalspawnpoint set, and it seems to work which is a huge concern since that means someone can troll and set a spawnpoint inside of a giant volcano.

**To Reproduce**
Deop yourself and try running those commands.

**Expected behavior**
Users without permissions/op aren't allowed to run the commands

**Screenshots**
None, i'll provide them if there's a doubt. nooo, i'm not laaazy... maybe a little bit.

**Comment by DaFuqs** [comment]
Absolutely. I will make the commands required permission level configurable.

**Comment by DaFuqs** [comment]
v1.5.1 has a configurable permission level for the commands. It defaults to 2 (like vanilla /spawn)

**Comment by MrRubberDucky** [comment]
> v1.5.1 has a configurable permission level for the commands. It defaults to 2 (like vanilla /spawn)

Thanks :)
