### ISSUE TITLE
[BUG] [1.19] GlobalSpawn spawn point is always in the overworld

### ISSUE THREAD

**Issue by nu11une** [DaFuqs/GlobalSpawn#13]
**Describe the bug**
Players will always respawn in the overworld regardless of which dimension the GlobalSpawn spawn point is set in. They will respawn at the correct coordinates, but incorrect dimension.

**To Reproduce**
1. Install GlobalSpawn
2. Use `/globalspawnpoint set` in a non-overworld dimension
3. Die and respawn

**Comment by DaFuqs** [comment]
That time I thought I actually tested everything there is another thing slipping through the cracks.
I will get that fixed, thank you!

**Comment by stanlystark** [comment]
The same error in version 1.18.2. Also, after the destruction of the bed, the first spawn occurs in the wrong dimension (correct coordinates), the subsequent respawns are correct

**Comment by DaFuqs** [comment]
Does this only happen for you in modpacks, or with GlobalSpawn alone?

**Comment by stanlystark** [comment]
> Does this only happen for you in modpacks, or with GlobalSpawn alone?

Only with GlobalSpawn. I tried to fix the bug with the bed myself, but my knowledge is not enough :)

**Comment by DaFuqs** [comment]
I will look into it and will let you know. :)

**Comment by DaFuqs** [comment]
done
