### ISSUE TITLE
[Feature Request] Allow setting respawn point seperately

### ISSUE THREAD

**Issue by amnotbananaama** [DaFuqs/GlobalSpawn#3]
Thank you for fixing the bugs I reported yesterday so quickly! The mod is working great :) This is just a feature request that I thought of while using GlobalSpawn. It would be awesome if we could set the initial spawn point (where players spawn the first time they join the server) **separately** from the respawn point (where players respawn to without a valid bed/respawn anchor when they die).

This could be set by a complimentary command, eg. `/globalrespawnpoint`. The usecase for this would be having a tutorial area for the modpack/datapack at the initial spawn point, where players learn about the features of the pack. Separately, when players die, they could respawn in a different area since the tutorial information will feel kind of cheesy after many deaths.
<details>
  <summary>Example config file:</summary>
  
```json5
{
        "active": true,
        "spawnDimension": "minecraft:tutorial",
        "spawnX": 0,
        "spawnY": 63,
        "spawnZ": 0,
        "respawnDimension": "minecraft:overworld",
        "respawnX": -49,
        "respawnY": 90,
        "respawnZ": 200,
}
```
</details>

I hope this request makes sense. This is just something I thought of while playing around with the mod, don't worry about it if you're not able to do this at all or if you need to find the time for it. Thank you!

**Comment by DaFuqs** [comment]
Very reasonable request, sounds useful.
I'll see what I can do.

**Comment by DaFuqs** [comment]
Added via 3db437d6222c56bcef0fb434cd99ac3359af0bba. ✔
Will be released soon.

**Comment by DaFuqs** [comment]
Done!
