### ISSUE TITLE
[BUG] [StarrySky] Nether portals do not create Nether portals in destination dimensions

### ISSUE THREAD

**Issue by Noaaan** [DaFuqs/GlobalSpawn#4]
**Describe the bug:**
Serverside issue (not tested on clientside). Creating a nether portal does not lead you to to the starry skies nether, but instead softlocks you forcing an admin to kick you from the server.

**To Reproduce:**
Create a nether portal in the starry sky dimension on a dedicated server.
Attempt to go trough it, you will get stuck in an infinite loading screen.

**Comment by DaFuqs** [comment]
On my is the teleportation stuff wonky. 
Fixed via https://github.com/DaFuqs/StarrySky/commit/32af743b6a9156ac284e7c5306f5b16e80c6efe9
Next release soon.
