### ISSUE TITLE
[BUG] ./gradlew runClient does not work

### ISSUE THREAD

**Issue by spaceclouds42** [DaFuqs/GlobalSpawn#7]
**Describe the bug**
I ran `./gradlew runClient` because there was no run configuration. The mod itself built fine, but when the Minecraft Client started, it crashed after finishing loading the config file.
```
[10:25:02] [main/INFO] (Minecraft) Setting user: Player795
[10:25:03] [main/INFO] (globalspawn) Loading config file...
[10:25:03] [main/INFO] (globalspawn) Finished loading config file.
[10:25:04] [main/INFO] (Indigo) [Indigo] Registering Indigo renderer!
---- Minecraft Crash Report ----
```
I was trying to do this because I wanted to work on a implementing #6, but the mod won't load ;-;

**To Reproduce**
~~Open project in IDEA, open Terminal tab,~~ Set your path to /GlobalSpawn/ in a terminal, run `./gradlew runClient`

**Expected behavior**
For Minecraft to open

[crash-2021-01-11_10.25.06-client.txt](https://github.com/DaFuqs/GlobalSpawn/files/5796629/crash-2021-01-11_10.25.06-client.txt)

**Comment by DaFuqs** [comment]
I've added the idea settings to the repo. If everything else is missing just let me know. :)
